[package]
name = "oaapi"
version = "0.1.1"
edition = "2021"
authors = ["Mochineko <t.o.e.4315@gmail.com>"]
rust-version = "1.76"
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "An unofficial Rust client for the OpenAI API."
documentation = "https://docs.rs/oaapi"
repository = "https://github.com/mochi-neko/oaapi"
categories = ["api-bindings", "science"]
keywords = ["oepnai", "rest", "api", "client", "machine-learning"]

[package.metadata.docs.rs]
all-features = true

[lib]
path = "src/lib.rs"

[features]
default = []
audio = ["dep:subtp"]
chat = []
full = ["audio", "chat"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "^1.5.*"
reqwest = { version = "^0.11.*", features = ["multipart", "json", "stream"] }
serde = { version = "^1.0.*", features = ["derive"] }
serde_json = "^1.0.*"
thiserror = "^1.0.*"
tokio = { version = "^1.35.*", features = ["fs"] }
subtp = { version = "^0.2.*", optional = true }
pin-project = "1.1.*"
futures-core = "0.3.*"

[dev-dependencies]
anyhow = "1.0.79"
base64 = "0.21.7"
clap = { version = "4.4.18", features = ["derive"] }
ctrlc = "3.4.2"
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1.15"
